# Generated by Django 6.0.6 on 2026-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text='The role this question is for (e.g., Frontend Developer)', max_length=255)),
                ('text', models.TextField(help_text='The actual question to ask')),
                ('expected_answer', models.TextField(blank=True, help_text='Guidance for the interviewer on what a good answer looks like', null=True)),
            ],
        ),
    ]
