# Generated by Django 6.0.6 on 2026-09-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('INTERVIEWER', 'Interviewer'), ('MANAGEMENT', 'Management'), ('COMPANY', 'Company')], default='CANDIDATE', max_length=20),
        ),
    ]
