# Generated by Django 6.0.6 on 2026-09-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
