# Generated by Django 6.0.6 on 2026-09-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='designation',
            field=models.CharField(default='Unspecified', help_text='The role/designation this interview is for', max_length=255),
        ),
    ]
