# Generated by Django 6.0.6 on 2026-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewers', '0003_interview_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='communication_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='problem_solving_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='technical_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
