# Generated by Django 6.0.6 on 2026-09-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewers', '0004_interview_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='confidence_score',
            field=models.IntegerField(blank=True, help_text='Out of 10', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='culture_fit_score',
            field=models.IntegerField(blank=True, help_text='Out of 10', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interviewerprofile',
            name='earnings_per_interview',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='interview',
            name='communication_score',
            field=models.IntegerField(blank=True, help_text='Out of 15', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='problem_solving_score',
            field=models.IntegerField(blank=True, help_text='Out of 25', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='technical_score',
            field=models.IntegerField(blank=True, help_text='Out of 40', null=True),
        ),
    ]
