# Generated by Django 6.0.6 on 2026-09-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interviewers', '0006_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
