# Generated by Django 6.0.6 on 2026-09-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Applied'), ('ASSIGNED', 'Interviewing'), ('INTERVIEWED', 'Evaluated'), ('OFFERED', 'Offered'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
