# Generated by Django 6.0.6 on 2026-09-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_alter_candidateprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='designation',
            field=models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('Data Scientist', 'Data Scientist'), ('Product Manager', 'Product Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('QA Engineer', 'QA Engineer'), ('Other', 'Other')], default='Software Engineer', max_length=100),
        ),
    ]
