# Generated by Django 6.0.6 on 2026-09-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0004_candidateprofile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='designation',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='designations',
            field=models.CharField(blank=True, help_text='Comma-separated list of applied designations', max_length=500, null=True),
        ),
    ]
