# Generated by Django 6.0.6 on 2026-09-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0007_practicesession_practicemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='PracticeMessage',
        ),
        migrations.DeleteModel(
            name='PracticeSession',
        ),
    ]
