# Generated by Django 6.0.6 on 2026-09-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0002_jobpost_interviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlocktransaction',
            name='outcome',
            field=models.CharField(choices=[('EVALUATING', 'Evaluating'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='EVALUATING', max_length=20),
        ),
    ]
