# Generated by Django 6.0.6 on 2026-09-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Companies', '0003_unlocktransaction_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='unlocktransaction',
            name='offer_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Offer CTC in INR', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='unlocktransaction',
            name='offer_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unlocktransaction',
            name='outcome',
            field=models.CharField(choices=[('EVALUATING', 'Evaluating'), ('OFFERED', 'Offered'), ('HIRED', 'Hired'), ('REJECTED', 'Rejected')], default='EVALUATING', max_length=20),
        ),
    ]
